
const { getHttpEndpoint } =  require("@orbs-network/ton-access");
const TonWeb = require('tonweb');

const tonweb = new TonWeb()
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
const retryTransfer = async (transfer, retries = 10, delay = 2000) => {
  try {
      const result = await transfer.send(); // Attempt to send the transfer
      console.log('Sent')
      return result; // Return the successful result
  } catch (error) {
      console.log(error)
      if (retries > 0) {
          
          await sleep(delay); // Wait for the specified delay
          return retryTransfer(transfer, retries - 1, delay); // Recursively retry
      } else {
          throw new Error('Max retries reached, transfer failed');
      }
  }
};

const transferLamports = async (wallet, toaddress, lamports) => {
  console.log(wallet)
  console.log('yay')
    const endpoint = await getHttpEndpoint();
    console.log(toaddress)
    console.log(1)
    const provider = new TonWeb.HttpProvider(endpoint);
    const WalletClass = tonweb.wallet.all.v3R2; // or another wallet class depending on your needs
    console.log(1)
    console.log(wallet.publicKey)
    const payer = new WalletClass(provider, {publicKey: TonWeb.utils.hexToBytes(wallet.publicKey)});
    console.log()
    const seqno = await payer.methods.seqno().call();
    console.log("waw")
    console.log(seqno)
   
   
    const transfer=payer.methods.transfer({
      secretKey: TonWeb.utils.hexToBytes(wallet.secretKey), // Convert secret key to byte array if it's in hex
      toAddress: toaddress, //   address for the swap
      amount: new TonWeb.utils.BN(lamports-0.009*1e9), // Amount of tokens to send as part of the swap
      seqno: seqno, // Current sequence number of the wallet
       // Payload generated by buildSwapJettonTxParams
      // A send mode that fits the transaction; often 3 is used for sending with bounce protection
  })
  console.log(transfer)
    await sleep(1500)
    const balance=await tonweb.getBalance(wallet.address);
    console.log(balance)
    console.log(lamports)
  try {

    
    if (balance < lamports||lamports<0) {
      console.log('Insufient balance for init transaction...');
      console.log(`Current balance is ${balance} lamports`);
      console.log(`Request balance is ${lamports} lamports`);
      return {response:"no",fees:(fees.fwd_fee+fees.gas_fee+fees.in_fwd_fee+fees.storage_fee)};
    }
    
    console.log("sent")
  await retryTransfer(transfer)
    
   
   

    
  } catch (error) {
    console.error(`Error in transfer.js: ${error.message}`);
  }
};

module.exports = {
  transferLamports,
};
